---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-odcs-compose
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to use for this task
    - name: KT_PATH
      type: string
      description: path to mount keytab
      default: /tmp/kt
  workspaces:
    - name: workdir
      description: |
        Working directory that will be used for reading configuration files
        and writing the output
    - name: keytab-secret
      description: for storing keytab secret
      mountPath: "$(params.KT_PATH)"
  results:
    - name: repodir_path
      description: Directory to write the result .repo files.
  steps:
    - name: generate-odcs-compose
      image: "$(params.IMAGE)"
      env:
        - name: KRB5CCNAME
          value: /tmp/krb5ccname
        - name: KRB5_CLIENT_KTNAME
          value: "$(params.KT_PATH)/keytab"
        - name: KRB5_TRACE
          value: /dev/stdout
      script: |
        #!/bin/bash
        set -ex

        repodir_path="$(workspaces.workdir.path)/repos"

        cd "$(workspaces.workdir.path)"

        odcs_compose_generator \
          --compose-input-yaml-path compose_inputs.yaml \
          --compose-dir-path "${repodir_path}"

        echo "$repodir_path" > $(results.repodir_path.path)
